version: '3.9'

services:
  web:
    container_name: burgerzilla
    image: burgerzilla
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/BurgerZilla_TESTDB
    depends_on:
      - db
  db:
    container_name: db 
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=BurgerZilla_TESTDB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}